CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE roles
(
  id BIGSERIAL PRIMARY KEY,
  uuid UUID NOT NULL,
  version INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE roles_history
(
  rev BIGINT,
  revtype SMALLINT,
  id BIGSERIAL PRIMARY KEY,
  uuid UUID,
  version INTEGER,
  updated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  name VARCHAR(255)
);
