CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE user_role (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK (name IN ('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN')),
    uuid UUID NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE user_role_history (
  rev BIGINT,
  revtype SMALLINT,
  id BIGSERIAL PRIMARY KEY,
  uuid UUID,
  version INTEGER,
  updated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  name VARCHAR(50) NOT NULL CHECK (name IN ('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN'))
);