spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car
    username: postgres
    password: d2d2d2d2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  flyway:
    enabled: true
    baselineOnMigrate: true

logging:
  level:
    ROOT: INFO
    org:
      flywaydb: DEBUG
      hibernate: DEBUG

backend:
  app:
    jwtSecret: shopoeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI
    jwtExpirationMs: 80000000000